# rust
[[language]]
name = "rust"
auto-format = true

[language-server.rust-analyzer.config.check]
command = "clippy"

[language-server.rust-analyzer.config.cargo]
allFeatures = true

# python
[[language]]
name = "python"
auto-format = true

[language.debugger]
name = "debugpy"
transport = "stdio"
command = "uv"
args = ["run", "python", "-m", "debugpy"]

[[language.debugger.templates]]
name = "source"
request = "launch"
completion = [{ name = "entrypoint", completion = "filename", default = "." }]
args = { mode = "debug", program = "{0}" }

# toml
[[language]]
name = "toml"
auto-format = true

[language-server.taplo]
config = {}

# markdown
[[language]]
name = "markdown"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "md"] }
auto-format = true
comment-tokens = ["-", "+", "*", "- [ ]", ">"]

# emmet
[language-server.emmet-lsp]
command = "emmet-language-server"
args = ["--stdio"]

# typescricpt
[[language]]
name = "typescript"
formatter = { command = 'deno', args = ["fmt", "-"] }
auto-format = true

# html
[[language]]
name = "html"
scope = "text.html.basic"
injection-regex = "html"
file-types = [
  "html",
  "htm",
  "shtml",
  "xhtml",
  "xht",
  "jsp",
  "asp",
  "aspx",
  "jshtm",
  "volt",
  "rhtml",
  "cshtml",
]
block-comment-tokens = { start = "<!--", end = "-->" }
language-servers = ["vscode-html-language-server", "emmet-lsp"]
auto-format = true

# css
[[language]]
name = "css"
auto-format = true

# svelte
[[language]]
name = "svelte"
language-servers = [
  "emmet-lsp",
  "tailwindcss-ls",
  "vscode-css-language-server",
  "svelteserver",
]
formatter = { command = "prettier", args = [
  "--plugin",
  "prettier-plugin-svelte",
  "--parser",
  "svelte",
] }
auto-format = true

# django
[[language]]
name = "htmldjango"
scope = "source.htmldjango"
injection-regex = "htmldjango"
roots = []
file-types = []
indent = { tab-width = 2, unit = " " }
language-servers = ["djlsp", "vscode-html-language-server"]
formatter = { command = "djlint", args = [
  "--reformat",
  "--profile=django",
  "--indent=2",
  "--blank-line-after-tag=load,extends,include,endblock",
  "--format-css",
  "--format-js",
  "-",
] }
